name: djsync
description: "A simple application to check and edit data of a firebird database"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  asp: ^2.0.3
  flutter:
    sdk: flutter
  flutter_modular: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4

flutter_icons:
    android: true
    ios: true
    image_path: assets/images/icon/icon.ico

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/logo.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-VariableFont_wght.ttf
        - asset: assets/fonts/montserrat/static/Montserrat-Bold.ttf
        - asset: assets/fonts/montserrat/static/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Italic-VariableFont_wght.ttf
